import type { Metadata } from "next";
import "@/styles/globals.scss";
import { CartSidebar, Footer, LoginSidebar, Navbar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {/* <CartSidebar/> */}
        {/* <LoginSidebar/> */}
        {children}
        <Footer/>
      </body>
    </html>
  );
}
